### ISSUE TITLE
Dist folder option

### ISSUE THREAD

**Issue by scriptPilot** [scriptex/create-pwa#115]
Thanks for this piece of code - very helfpul.

Enhancement: 

Would be helpful to specify in the CLI call the dist folder where all files and folders are generated.
Today, they are all created in the main folder.

**Comment by scriptex** [comment]
Thanks for raising this, it looks like a nice improvement!
I will include it in the upcoming release. 
For more details please check out the PR.

**Comment by scriptex** [comment]
This is added as a new CLI flag `--output` in the latest release which is available on Github and NPM.

**Comment by scriptPilot** [comment]
Thanks a lot for the quick implementation 👍
