### ISSUE TITLE
Error with doubled file names 

### ISSUE THREAD

**Issue by scriptPilot** [scriptex/create-pwa#116]
Default settings.

<img width="567" alt="Bildschirmfoto 2022-12-26 um 01 21 20" src="https://user-images.githubusercontent.com/19615586/209485695-947ae1c0-fa20-4673-839c-e51136293d10.png">

**Comment by scriptex** [comment]
Hey, thanks for finding this out :) 
I will fix it with the next release.
More details can be found in the linked PR :)

**Comment by scriptex** [comment]
This is now fixed in the latest release which is available on Github and NPM.

**Comment by scriptPilot** [comment]
Perfect, thanks for the quick resolution!
